// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTZH__iCCeDo_ODxllzIGweBkz_sVt-H0',
    appId: '1:587495464288:android:909b1fe38b109d2d6dd205',
    messagingSenderId: '587495464288',
    projectId: 'myshop-3abf1',
    databaseURL: 'https://myshop-3abf1-default-rtdb.firebaseio.com',
    storageBucket: 'myshop-3abf1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC59j2Qeark4Rlby_RYL_jSJT0I5-SBkO4',
    appId: '1:587495464288:ios:4c7d2a9d14706ef16dd205',
    messagingSenderId: '587495464288',
    projectId: 'myshop-3abf1',
    databaseURL: 'https://myshop-3abf1-default-rtdb.firebaseio.com',
    storageBucket: 'myshop-3abf1.appspot.com',
    iosClientId: '587495464288-dibtsc30jgcn3nh3l4mg127ob68d59ft.apps.googleusercontent.com',
    iosBundleId: 'com.example.myshop',
  );
}
